name: deploy to ec2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up ssh key
      run: |
        echo "${{ secrets.EC2_PRIVATE_KEY }}" >> private_key.pem
        chmod 600 private_key.pem

    - name:
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
          cd aws-test &&
          git pull origin main &&
          npm install &&
          pm2 restart all || pm2 start app.js
        "
